name: Packer Build

on:
  push: {}
    # branches: [ master ]
  pull_request: {}
    # branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/cache@v1
      with:
        path: packer_cache
        key: packer_cache
        restore-keys: packer_cache

    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build
      run: packer/build base.json

    - name: release
      id: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: v${{ github.run_number }}
        draft: true

    - name: upload_image
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./final.img.gz
        asset_name: final.img.gz
        asset_content_type: application/gzip

    - name: upload_sha
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./final.img.gz.sha256
        asset_name: final.img.gz.sha256
        asset_content_type: text/plain
